### ISSUE TITLE
ks_abc when run with plot=False still plots the graph

### ISSUE THREAD

**Issue by RNarayan73** [shakedzy/dython#151]
Thanks for the suggestion, @Socvest. Your workaround does seem to arrest the problem and reduce run time significantly. I've included it below in the code for comparison but commented it out to highlight the initial problem.

Here you go @shakedzy !
```
from sklearn.datasets import make_classification
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from dython.model_utils import ks_abc

def ks_abc_score(y_true, y_prob):
    return ks_abc(y_true, y_prob, plot=False)['abc']
#     res = ks_abc(y_true, y_prob, plot=False)
#     plt.close()
#     return res['abc']


X, y = make_classification(n_samples=100, n_features=4)

grid_search_pipe = GridSearchCV(Pipeline([('clf', SGDClassifier(loss='log_loss'))]), 
                                param_grid={'clf__alpha': [10e-02, 10e-01]}, 
                                scoring=make_scorer(ks_abc_score, needs_proba=True), 
                                verbose=1
                               )
grid_search_pipe.fit(X, y)

y_prb = grid_search_pipe.predict_proba(X)
ks_abc_score(y, y_prb[:, 1])
```
Note that for each of the 10 fits in the example above, it generates a ks_abc chart in jupyter, which takes up significant memory and processing time. The call to ks_abc_score function adds another chart!
@Socvest's workaround does cut down on the run time and presumably memory, but makes the function to calculate a score look very awkward.

Hope this helps in getting to a fix.

Regards
Narayan

_Originally posted by @RNarayan73 in https://github.com/shakedzy/dython/issues/147#issuecomment-1483908732_

**Comment by shakedzy** [comment]
hey @RNarayan73 - thanks for the script. I just ran it on Jupyter Lab, and indeed got several plots. I ran the exact same thing from a Python console and a as Python script, and got no plots at all. This again concludes that the issue here is not `ks_abc` or `dython`, but how Jupyter works with `matplotlib` plots under the hood. So unfortunately, I will not make a fix for this, as there's nothing broken, and I too recommend using `plt.close()` to fix this in Jupyter.
