### ISSUE TITLE
Possible bug in nominal.py

### ISSUE THREAD

**Issue by iyer-karthik** [shakedzy/dython#5]
Shouldn't line 25 in `nominal.py` be 
`xy_counter = Counter(list(product(x,y)))` instead of `xy_counter = Counter(list(zip(x,y)))`?
The reasoning here being that when computing the joint distribution of `(x, y)`, we would iterate over all possible pairs? 

In the same vein, line 26 calculates `total_occurences` which is then used in line 29. 
However for computing the joint probability `p_xy`, shouldn't `total_occurences` be changed to `sum(xy_counter.values())`? 

I guess I am not sure about the validity of the calculations here. Can I work on this issue?

**Comment by shakedzy** [comment]
Hi!
First of all, You are of course welcomed to work on any issue you'd like - all contributions and bug reports are very welcomed :)

As for you questions - I'll try to explain my approach. Let's look at the Conditional Entropy formula from [Wikipedia](https://en.wikipedia.org/wiki/Conditional_entropy): 
![screen shot 2019-03-07 at 11 22 36](https://user-images.githubusercontent.com/15704705/53945957-6c3d3480-40cb-11e9-8752-dcdfadfdc0be.png)
Note the mild differences between my code and this formula: I do H(x|y) while Wikipedia is doing H(y|x). also, the numerator and denominator are reversed due to the minus sign in Wikipedia's version which I omitted. Mathematically, it's the same due to the log function.

Let's assume the following example: `conditional_entropy(x=[0,1,0,1,1], y=[0,0,1,1,1])`
We need to calculate p(x,y) and p(y) [which is p(x) is Wikipedia]. Using the counters, what I get is:
```
y_counter = Counter{0: 2, 1: 3}
xy_counter = Counter{(0,0): 1, (1,0): 1, (0,1): 1, (1,1): 2}
```
These are just the count of the occurrences, and so in order to get the empiric probability, these counts are needed to be divided by the overall number of samples. This is what `total_occurrences` is for. both `sum(y_counter.values())` and `sum(xy_counter.values())` will yield the same result (as you can see in out example, where `total_occurrences = 5`, but as `y_counter` will probably have less elements, I decided to sum over it. The next phase is the for loop over all (x,y) tuples, which is the equivalent of the summation in the Wikipedia formula.
So, `xy_counter = Counter(list(product(x,y)))` will not yield the desired result - we're not looking for the product of x and y, but rather all possible tuples.

Let me know if you think I got something wrong.

**Comment by iyer-karthik** [comment]
Hi, 

Thanks for your reply and your work! I still think there is a problem with the way the conditional entropy is calculated. Let me outline the reasons. 

When you are computing the joint probability distribution`p(x,y)`, you are not considering all possible values for the (x, y) pairs. For example, when `x = [0, 1, 0, 1, 0]` and `y = [0, 0, 1, 2, 4]`, there are two unique values for x and 4 unique values for y. Thus there should be 8 (two times 4) possible pairs of (x, y) values, since we wish to compute the joint probability distribution of (x, y). Setting `xy_counter = Counter(list(zip(x, y)))`  gives `Counter({(0, 0): 1, (1, 0): 1, (0, 1): 1, (1, 2): 1, (0, 4): 1})` implying for instance that the pair (1, 4) is never formed, which is incorrect. The joint probability distribution must take in to account all possible (x, y) pairs. 

A second reason why using `zip(x, y)` is incorrect is the following. Let's say `x = [0, 1, 0, 1]` and `y = [1. 2. 3. 4. 5]`. (Having x and y of different lengths is valid, since the two random variables x and y for which the conditional entropy is being computed need not have supports of equal length.). Setting `xy_counter = Counter(list(zip(x, y)))` gives `Counter({(0, 1): 1, (1, 2): 1, (0, 3): 1, (1, 4): 1})`. From here, computing the marginal probability of y, namely `P(y=5)` gives 0 (since there no pair (x,y) for which y=5 gets formed by your logic), which is incorrect, since the marginal probability `P(y=5) = 1`. 

`itertools.product(x, y)` gives the Cartesian product of x and y, i.e all possible pairs of (x, y). Changing `xy_counter`  to  `Counter(list(product(x,y)))` solves this problem. 

Moreover, one can see now why `sum(xy_counter.values())` needs to be used. 

When computing the joint distribution of (x, y), all possible pairs of (x, y) need to be considered. As noted in the Wikipedia formula for conditional entropy that you cited, the summation in the formula happens for all possible pairs of (x, y) values in the joint support.

I hope I provided clarification on this issue! I will be happy to work on this :)

**Comment by shakedzy** [comment]
I think I see what causes the confusion. 
Please remember that `x` and `y` are not the possible values of two variables, but rather the empirical results of two simultaneously performed tests. For example, in my example, `x=[0,1,0,1,1], y=[0,0,1,1,1]`, these can be seen as the results of flipping two coins simultaneously for 5 times. Your example of `x = [0, 1, 0, 1, 0], y = [0, 0, 1, 2, 4]` can be seen as the results of sampling two numbers from some arbitrary distribution for 5 times. This means that `x` and `y` _must be_ of the same length, as otherwise it means you sample only one number rather than two, which is not allowed.
Also, the pair (1,4) is irrelevant, for two reasons - first, you might think that (1,4) is a possible result which never accrued, but perhaps it is not allowed. Maybe the distribution which we sample from doesn't allow two numbers which have a distance of 3. You don't always know what generated the numbers you work with. Second, mathematically, if (1,4) never happened, then p(x,y) = 0, and then the formula gives 0*log(0) = 0. Therefore it has no impact on the summation.
Hope this makes things clear :)

**Comment by iyer-karthik** [comment]
Hi ,
Thanks for your reply. I think there is a fundamental problem here that is not being understood. 
Let's assume, as you say, that `x` and `y` are results of two simultaneously performed tests. Let's say these are independent of each other. What would you say the joint probability `(x, y)` is? 

Let's go by the example  that `x = [0, 1, 0, 1, 0], y = [0, 0, 1, 2, 4]`. As per your claim `p(x=1, y=4) = 0`. Since these are independent, `p(x=1, y=4) = p(x=1)*p(y=4)`. However the LHS is 0 as per your claim, but the RHS is 2/5*1/5 = 2/25. Do you see why this is a problem?

For more reference on why a cartesian grid is needed, this is a good reference: https://github.com/dit/dit/blob/master/dit/samplespace.py

**Comment by shakedzy** [comment]
Hi :) I think it is important to emphasize that the  `conditional_entropy` function calculates the Conditional Entropy based on _empirical_ results only, without adding any other assumptions. Therefore, according to the empirical results of `x = [0, 1, 0, 1, 0], y = [0, 0, 1, 2, 4]`, p(1,4) is indeed 0, because it never happened _empirically_. Saying that x and y are independent of each other is an _assumption_ you made, and is not found in the data. This is what causes the 0 = 2/25 problem, as it compares empirical results to assumptions. If indeed x and y are independent, then eventually there will be a pair (1,4) in the data set.
This is a great thread, thank you very much!

**Comment by iyer-karthik** [comment]
Hi, 
Looks like I am not convinced by your arguments and you by mine. Good luck!

**Comment by shakedzy** [comment]
Thanks! :)
