### ISSUE TITLE
Asymmetry of eta

### ISSUE THREAD

**Issue by lucazav** [shakedzy/dython#85]
The `associations()` function return a symmetric value for correlation ratio (eta), i.e. the value is the same even if you swap the direction of the two variables. Eta is [non-symmetric by definition](https://encyclopediaofmath.org/wiki/Correlation_ratio). In order to calculate the opposite side of direction, could it make sense to turn the categorical variable into an integer by giving an index to each category, and then calculate the opposite direction?

**Comment by shakedzy** [comment]
Hi @lucazav - the reverse calculation of correlation ratio only make sense when both variables are numerical. Otherwise, what is the meaning of the variance of a categorical value? What is the variance of _day_of_week_ ? Even if you translate it to numerical values (1-7 or 0-6), the variance has no real meaning. If, though, you have a categorical feature in your set that its numerical variance does have a meaning - then I see why you'll want this, but it is a very specific edge case.
